#!/usr/bin/env python3
"""Generate a PR comment from a specback-gate JSON report (exit 0 = post).

Reads the gate report JSON path from argv[1]. Writes the comment body to
the path in argv[2] (or /tmp/specback-drift-comment.md by default). Exits
0 with no output when there is nothing worth commenting on (no changes,
pass verdict).
"""
from __future__ import annotations

import json
import sys
from pathlib import Path


def main(argv: list[str] | None = None) -> int:
    argv = argv if argv is not None else sys.argv[1:]
    report_path = Path(argv[0])
    comment_path = Path(argv[1]) if len(argv) > 1 else Path(
        "/tmp/specback-drift-comment.md"
    )
    try:
        report = json.loads(report_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        print(f"post-comment.py: cannot read report: {exc}", file=sys.stderr)
        return 0

    verdict = report.get("verdict", "error")
    drift = report.get("drift", {})
    summary = drift.get("summary", {})
    changed = int(summary.get("changed_files", 0) or 0)
    orphaned = int(report.get("fix_refs", {}).get("orphaned", 0) or 0)

    # Nothing to report: pass verdict without warnings (regardless of
    # changed-file count — drift-free changes need no comment).
    if verdict not in ("fail", "warn") and not report.get("warnings"):
        return 0

    lines: list[str] = []
    lines.append("## 🤖 specback drift check")
    if verdict == "fail":
        lines.append("**Status: 🔴 FAIL — the spec is affected by this PR.**")
    elif verdict == "warn":
        lines.append("**Status: 🟡 WARN — check the notes below.**")
    else:
        lines.append("**Status: 🟢 PASS**")
    lines.append("")
    lines.append(f"- **Changed files**: {changed}")
    lines.append(
        f"- **Affected spec sections**: "
        f"{summary.get('affected_spec_sections', 0)}"
    )
    lines.append(
        f"- **New uncovered sources**: "
        f"{summary.get('new_uncovered_sources', 0)}"
    )
    lines.append(
        f"- **Deleted sources with refs**: "
        f"{summary.get('deleted_sources_with_refs', 0)}"
    )
    if orphaned:
        lines.append(
            f"- **Orphaned REFs**: {orphaned} "
            f"(run `scripts/fix-refs.py --apply`)"
        )
    warnings = report.get("warnings") or []
    if warnings:
        lines.append("")
        lines.append("**Warnings:**")
        for w in warnings:
            lines.append(f"- {w}")
    lines.append("")
    lines.append(
        "Update the affected spec sections in this PR to keep the spec honest."
    )
    lines.append("")
    lines.append("> Generated by `specback-drift` GitHub Action (Issue #266).")
    comment_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
